# Generated by Django 5.1.5 on 2025-01-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_populate_message_rooms'),
    ]

    operations = [
    ]
